version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '05:00'
      timezone: 'Asia/Tokyo'
    ignore:
      - dependency-name: '@types/node'
        update-types: ['version-update:semver-major']
      # cf. https://github.com/octokit/auth-app.js/issues/282
      - dependency-name: '@octokit/auth-app'
